language: go
go:
- 1.12
script:
- go build -o jsdaddy .
- chmod 600 ./deploy_id_rsa.pem
- ssh-keyscan -H 89.208.199.114 >> ~/.ssh/known_hosts
- scp -i ./deploy_id_rsa.pem ./jsdaddy ubuntu@89.208.199.114:/home/ubuntu/backend
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_5462f8b61b0a_key -iv $encrypted_5462f8b61b0a_iv
  -in deploy_id_rsa.pem.enc -out ./deploy_id_rsa.pem -d
